name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Set your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-south-1  # Replace with your region
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 166426622475.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pythonflask-repo

      - name: Tag Docker image with ECR repository URL
        run: |
          docker tag pythonflask-repo:latest 166426622475.dkr.ecr.ap-south-1.amazonaws.com/pythonflask-repo:latest

      - name: Push Docker image to ECR
        run: |
          docker push 166426622475.dkr.ecr.ap-south-1.amazonaws.com/pythonflask-repo:latest
          
  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
            args: '{"text": "Workflow failed in job ${{ github.job }} at step ${{ github.job }} - ${{ github.workflow }}"}'

      

    
      
